GET http://localhost:5051/WeatherForecast 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHV5MTIzIiwianRpIjoiNmFjYjU4MWQtYzNmNi00MzNlLWFiMWUtYzc3NGEwMmVlNmMyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTY3NDgwODE2NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDUxIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDUxIn0.i2HDw_Hw8yqBsNYTefco6F1xCmFsmNkH0ATd3m8C0mg"
Content-Type: application/json